config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  root to:  "homes#top"
  post '/' => 'homes#top'
   get "home/about" => "homes#about"
   get "comics/search" => "comics#search"
  resources :comics do
  resources :reviews, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  resources :genres, only: [:new, :show, :create, :destroy]
 resources :users, only: [:show, :edit, :update]
 
# ゲストログイン
  post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :comics, dependent: :destroy
  validates :name, presence: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  
  def new
    @genre = Genre.new
    @genres = Genre.all
  end


  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_back(fallback_location: root_path)
    else
      @genres = Genre.all
      render :new
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to new_genre_path
  end
  

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/new.html.erb
<div class="container my-5">
  <% if @genre.errors.any? %>
     <font size="3" color="red">入力失敗しました。入力事項を確認してください</font>
　　<% end %>

  <div class="row mt-5">

    <div class="offset-sm-1 col-sm-4">

      <div class="form-wrap border rounded p-5">
        <div class="row d-flex justify-content-center">
            <strong>新規ジャンル登録</strong>
        </div>

        <%= form_with model: @genre, local:true do |f| %>

        <div class="form-group">
            <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="row">
            <%= f.submit "追加", class: "btn btn-primary mt-3 mx-auto" %>
        </div>

        <% end %>
      </div>
    </div>


  <div class="offset-sm-1 col-sm-5">

    <table class="table table-hover text-center">
      <thead>
        <tr>
          <th>ジャンル</th>
        </tr>
      </thead>

      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td>
            <%= link_to "削除する", genre_path(genre), method: :delete, class: "btn btn-primary btn-sm" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  </div>
</div>