config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  root to:  "homes#top"
  post '/' => 'homes#top'
   get "home/about" => "homes#about"
   get "comics/search" => "comics#search"
  resources :comics do
  resources :reviews, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  resources :genres, only: [:new, :show, :create, :destroy]
 resources :users, only: [:show, :edit, :update]
 
# ゲストログイン
  post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :comics, dependent: :destroy
   has_many :reviews, dependent: :destroy
   attachment :profile_image
   has_many :favorites, dependent: :destroy
   has_many :favorited_comics, through: :favorites, source: :comic


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user,only: [:edit,:show]

  def show
    @user = User.find(params[:id])
    @comics = @user.favorited_comics.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def correct_user
      @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to comics_path
    end
  end



  private
  def user_params
    params.require(:user).permit(:email, :name, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container my-5 custom-gutters-pro">

  <h1>プロフィール編集</h1>
  <%= form_with model:@user, local:true do |f| %>

  <div class="row mt-5 m-5">
    <div class="col md-5">
      <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, fallback: "no_image.jpg", onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev' %>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: 'img_field' %>
    </div>
    
    <div class="col md-4 m-5">
      <div class="profile-name"><label for="inputName">名前</label></div>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      <div>
        <label for="inputEmail">メールアドレス</label>
      </div>
      <%= f.text_field :email, autofocus: true, id:"inputEmail", placeholder:"メールアドレス", class: "form-control col-sm-8"%>
      <%= f.submit "変更を保存" %>
    </div>
  </div>
  <% end %>
</div>

<script type="text/javascript">
    function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('.img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $('.img_field').change(function () {
    readURL(this);
  });
</script>

app/views/users/show.html.erb
<div class="container py-5 custom-gutters-pro">

  <h1>マイページ</h1>

  <div class="row mt-5 m-5">
    <div class="col md-5">
      <%= attachment_image_tag @user, :profile_image, :fill, 170, 170, fallback: "no_image.jpg" %>
    </div>
    <div class="col md-4 m-5">
      <h2 class="profile-name">名前：<%= @user.name %></h2>
      <% if @user.id == current_user.id %>
          <%= link_to "プロフィール編集", edit_user_path(@user) %>
      <% end %>
    </div>
  </div>
</div>

<div class="container custom-gutters-pro">
    <h1>お気に入り作品</h1>

    <div class="row">
      <% @comics.each do |comic| %>
        <div class="col col-12 col-md-2 col-lg-2 m-lg-2">
          <%= link_to comic_path(comic.id) do %>
          <p><%= attachment_image_tag comic, :image, size: "120x200", format: 'jpeg', fallback: "no_image.jpg" %></p>
          <% end %>


          <div class="">
            <span><%= comic.title %></span>
            <% if comic.favorited_by?(current_user) %>
            <span>
            <%= link_to comic_favorites_path(comic), method: :delete do %>
            ♥<%= comic.favorites.count %>
            <% end %>
            </span>
            <% else %>
            <span>
            <%= link_to comic_favorites_path(comic), method: :post do %>
            ♡<%= comic.favorites.count %>
            <% end %>
            </span>
            <% end %>
          </div>
  
           <script>
            $("#star-index-<%=comic.id%>").raty({
             size: 36,
             starOn: "<%= asset_path('star-on.png') %>",
             starOff: "<%= asset_path('star-off.png') %>",
             starHalf: "<%= asset_path('star-half.png') %>",
            // scoreName: 'review[rate]',
             half: true,
             readOnly: true,
             score: "<%= comic.reviews.average(:rate).to_f.round(1) %>",
           });
          </script>
           <div id="star-index-<%= comic.id %>"></div>
        </div>
      <% end %>
<%= paginate @comics %>
    </div>

</div>