config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  root to:  "homes#top"
  post '/' => 'homes#top'
   get "home/about" => "homes#about"
   get "comics/search" => "comics#search"
  resources :comics do
  resources :reviews, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  resources :genres, only: [:new, :show, :create, :destroy]
 resources :users, only: [:show, :edit, :update]
 
# ゲストログイン
  post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/comic.rb
class Comic < ApplicationRecord

   belongs_to :user
   attachment :image
   has_many :reviews, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorited_users,  through: :favorites, source: :user 
   belongs_to :genre


   validates :image, presence: true
   validates :author, presence: true
   validates :publisher, presence: true
   validates :title, presence: true
    validates :genre_id, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(method,word)
    if method == "forward_match"
            @comics = Comic.where("title LIKE ?","#{word}%")
    elsif method == "backward_match"
            @comics = Comic.where("title LIKE ?","%#{word}")
    elsif method == "perfect_match"
            @comics = Comic.where(title: "#{word}")
    elsif method == "partial_match"
            @comics = Comic.where("title LIKE ?","%#{word}%")
    else
            @comics = Comic.all
    end
  end

  def reviewd?(user)
    cnt = self.reviews.where(user_id: user.id).count
    return (cnt > 0)
  end

  def not_reviewd?(user)
    cnt = self.reviews.where(user_id: user.id).count
    return (cnt <= 0)
  end


end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :authenticate_user!
  

  def new
    @comic = Comic.new

  end

  def show
    @comic = Comic.find(params[:id])
    @review = Review.new
  end

  def index
    @comics = Comic.all
    @users = User.all
    @comics = Comic.page(params[:page]).reverse_order
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @genres = Genre.all
    else
      @genres = Genre.all
    end
  end

  def create
  @comic = Comic.new(comic_params)
  @comic.user_id = current_user.id
    if @comic.save
        redirect_to  comics_path
    else
        render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy
    @comic = Comic.find(params[:id])
    @comic.destroy
    redirect_to comics_path
  end

  def search
    method = params[:search_method]
    word = params[:search_word]
    @comics = Comic.search(method,word).page(params[:page]).reverse_order
    render :index
  end

  def correct_comic
        @comic = Comic.find_by(params[:id])
    unless @comic.user.id == current_user.id
      render  new_comic_path
    end
  end


  private
  def comic_params
    params.require(:comic).permit(:genre_id, :image, :title, :body, :author, :publisher, :is_active, :genre)
  end





end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-3">
      <div class="offset-1 col-10">
          <div class="row d-flex aline-items-center">

            <strong class="red-border px-3 pb-1">ジャンル検索</strong>
          </div>
          <div class="row mx-auto mt-3">
            <span class="brown-border text-center"><%= link_to "すべての商品", comics_path %></span>
          </div>
          <% if @genres.present? %>
            <% @genres.each do |genre| %>
              <%= link_to comics_path(genre_id: genre.id) do %>
                <div class="row mx-auto mt-3">
                  <span class="brown-border text-center"><%= genre.name %></span>
                </div>
              <% end %>
            <% end %>
          <% end %>
          </div>
      </div>

      <div class="col-9">
         <%= form_tag(comics_search_path , method: :get) do %>
                  <%= select(@search_content, :search_method, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]])%>
                  <%= text_field(@search_content, :search_word) %>
                  <%= submit_tag "作品名検索" %>
              <% end %>

      <div class="row">
        <h2 class="red-border px-3">
          <% if @genre.present? %>
            <h1><%= @genre.name %></h1>
          <% else %>
            <h1>すべての商品</h1>
          <% end %>
        </h2>
      </div>
　　　<% if user_signed_in? %>
        <div class="container custom-gutters-pro">
              <div class="row ">
              <% if @genre.present? %>
                  <% @genre.comics.each do |comic| %>
                  <div class="col col-12 col-md-2 col-lg-3">
                        <%= link_to comic_path(comic.id) do %>
                            <%= attachment_image_tag comic, :image, size: "120x200", format: 'jpeg', fallback: "no_image.jpg",class: 'rounded' %>
                        <% end %>
                        <div>
                          <strong class="red-border"><%= comic.title %></strong>
                          <% if comic.favorited_by?(current_user) %>
                              <%= link_to comic_favorites_path(comic), method: :delete do %>
                                ♥<%= comic.favorites.count %>
                              <% end %>
                          <% else %>
                              <%= link_to comic_favorites_path(comic), method: :post do %>
                                ♡<%= comic.favorites.count %>
                              <% end %>
                          <% end %>
                        </div>

                        <script>
                          $("#star-index-<%=comic.id%>").raty({
                           size: 36,
                           starOn: "<%= asset_path('star-on.png') %>",
                           starOff: "<%= asset_path('star-off.png') %>",
                           starHalf: "<%= asset_path('star-half.png') %>",
                          // scoreName: 'review[rate]',
                           half: true,
                           readOnly: true,
                           score: "<%= comic.reviews.average(:rate).to_f.round(1) %>",
                         });
                        </script>
                            <div id="star-index-<%= comic.id %>"></div>
                      </div>
                  <% end %>
              <% else %>
                  <% @comics.each do |comic| %>
                      <div class="col col-12 col-md-2 col-lg-3">
                        <%= link_to comic_path(comic.id) do %>
                            <%= attachment_image_tag comic, :image, size: "120x200", format: 'jpeg', fallback: "no_image.jpg",class: 'rounded' %>
                        <% end %>
                        <div>
                          <strong class="red-border"><%= comic.title %></strong>
                          <% if comic.favorited_by?(current_user) %>
                              <%= link_to comic_favorites_path(comic), method: :delete do %>
                                ♥<%= comic.favorites.count %>
                              <% end %>
                          <% else %>
                              <%= link_to comic_favorites_path(comic), method: :post do %>
                                ♡<%= comic.favorites.count %>
                              <% end %>
                          <% end %>
                        </div>

                        <script>
                          $("#star-index-<%=comic.id%>").raty({
                           size: 36,
                           starOn: "<%= asset_path('star-on.png') %>",
                           starOff: "<%= asset_path('star-off.png') %>",
                           starHalf: "<%= asset_path('star-half.png') %>",
                          // scoreName: 'review[rate]',
                           half: true,
                           readOnly: true,
                           score: "<%= comic.reviews.average(:rate).to_f.round(1) %>",
                         });
                        </script>
                          <div id="star-index-<%= comic.id %>"></div>
                      </div>
                  <% end %>
              <% end %>
          </div>
        </div>

    　<% else %>

      　<div class="container custom-gutters-pro">
        　<div class="row">
            <% if @genre.present? %>
              <% @genre.comics.each do |comic| %>
                <div class="col col-12 col-md-2 col-lg-3">
                  <%= link_to comic_path(comic.id) do %>
                    <%= attachment_image_tag comic, :image, size: "120x200", format: 'jpeg', fallback: "no_image.jpg",class: 'rounded' %>
                  <% end %>
                  <div>
                    <strong class="red-border"><%= comic.title %></strong>
                     ♡<%= comic.favorites.count %>
                  </div>
                  <script>
                    $("#star-index-<%=comic.id%>").raty({
                     size: 36,
                     starOn: "<%= asset_path('star-on.png') %>",
                     starOff: "<%= asset_path('star-off.png') %>",
                     starHalf: "<%= asset_path('star-half.png') %>",
                    // scoreName: 'review[rate]',
                     half: true,
                     readOnly: true,
                     score: "<%= comic.reviews.average(:rate).to_f.round(1) %>",
                   });
                  </script>
                  　<div id="star-index-<%= comic.id %>"></div>
                </div>
              <% end %>
            <% else %>
                <% @comics.each do |comic| %>
                <div class="col col-12 col-md-2 col-lg-3">
                  <%= link_to comic_path(comic.id) do %>
                    <%= attachment_image_tag comic, :image, size: "120x200", format: 'jpeg', fallback: "no_image.jpg",class: 'rounded' %>
                  <% end %>
                  <div>
                    <strong class="red-border"><%= comic.title %></strong>
                     ♡<%= comic.favorites.count %>
                  </div>
              　　　<div id="star-index-<%= comic.id %>"></div>
                  <script>
                    $("#star-index-<%=comic.id%>").raty({
                     size: 36,
                     starOn: "<%= asset_path('star-on.png') %>",
                     starOff: "<%= asset_path('star-off.png') %>",
                     starHalf: "<%= asset_path('star-half.png') %>",
                    // scoreName: 'review[rate]',
                     half: true,
                     readOnly: true,
                     score: "<%= comic.reviews.average(:rate).to_f.round(1) %>",
                   });
                  </script>
                </div>
                <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
       <%= paginate @comics %>
    </div>
  </div>
</div>

app/views/comics/new.html.erb
<div class="container my-5">

    <div class="row">
    　<h1>投稿フォーム</h1>
    </div>

    <% if @comic.errors.any? %>
     <font size="3" color="red">投稿失敗しました。入力事項を確認してください</font>
　　<% end %>

    <%= form_with model: @comic, local:true do |f| %>

    <div class="row mt-5">

        <div class="col-sm-4">
        <%= f.label :作品画像 %>
        <%= f.attachment_field :image, class: 'img_field' %>
        <%= attachment_image_tag @comic, :image, :fill, 150, 150, fallback: "no_image.jpg", onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev'  %>
        </div>

        <div class="col-sm-7">
            <div class="form-group row">
                <%= f.label :ジャンル, class: "col-sm-4" %>
                <%= f.collection_select :genre_id, Genre.all, :id, :name,  include_blank: "ジャンル選択", class: "form-control col-sm-8" %>
                <%= link_to new_genre_path do %>
                  <%= f.submit :ジャンル追加, class: "btn btn-primary" %>
                <% end %>
            </div>
            <div class="form-group row">
                <%= f.label :作者, class: "col-sm-4" %>
                <%= f.text_field :author, class: "form-control col-sm-8" %>
            </div>
            <div class="form-group row">
                <%= f.label :出版社, class: "col-sm-4" %>
                <%= f.text_field :publisher, class: "form-control col-sm-8" %>
            </div>
            <div class="form-group row">
                <%= f.label :作品名, class: "col-sm-4" %>
                <%= f.text_field :title, class: "form-control col-sm-8" %>
            </div>
            <div class="form-group row">
                <%= f.label :あらすじ, class: "col-sm-4" %>
                <%= f.text_area :body, class: "form-control col-sm-12" %>
            </div>
            <div class="col-sm-2 mt-auto ml-10">
        　       <%= f.submit :作品登録, class: "btn btn-primary" %>
            </div>
        </div>

    </div>

    <% end %>
</div>

<script type="text/javascript">
    function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('.img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $('.img_field').change(function () {
    readURL(this);
  });
</script>

app/views/comics/show.html.erb
<div class="container my-5 custom-gutters-pro">
 <div class="row">
   <div class="col md-5">
        <p><%= attachment_image_tag @comic, :image, size: "240x400", format: 'jpeg', fallback: "no_image.jpg" %></p>
        <% if @comic.user == current_user %>
            <%= link_to "作品を削除", comic_path(@comic), method: :delete %>
        <% end %>
  </div>

   <div class="col md-5 m-5">
        <p>作品名：<%= @comic.title %></p>
        <p>あらすじ：<%= @comic.body %></p>
        <p>ジャンル:<% if @comic.genre %><%= @comic.genre.name %><% end %></p>
        <p>作者：<%= @comic.author %></p>
        <p>出版社：<%= @comic.publisher %></p>
        <p id="star">平均評価 :</p>
        <p>コメント件数：<%= @comic.reviews.count %></p>
        <% if @comic.not_reviewd?(current_user) %>
                <%= form_with(model:[@comic, @review], local: true) do |f| %>
                    <div  id="form_star" >
                        <%= f.label :rate,'評価:' %>
                        <%= f.hidden_field :rate, id: :review_star %>
                    </div>
                    <%= f.text_area :body,placeholder: "未記入でも、評価のみで投稿できます" %>
                    <%= f.submit "投稿する" %>
                <% end %>
        <% else %>
          <h5 class="text-danger">評価済(再評価する場合は評価を削除してください)</h5>
        <% end %>
    </div>
</div>

     <div class="container my-5 custom-gutters-pro">
         <div class="col md-8 m-5">
         <table>
            <thead>
                <tr>
                 <th></th>
                 <th>名前</th>
                 <th>評価</th>
                 <th>コメント</th>
                 <th></th>
                </tr>
           </thead>
            <% @comic.reviews.each do |review| %>
           <tbody>
            <tr>
             <th><%= attachment_image_tag review.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></th>
             <th><%= review.user.name %></th>
             <th>
                 <div id="star-rate-<%= review.id %>"></div>
                  <script>
                  $('#star-rate-<%= review.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: "<%= review.rate || nil %>",
                  });
                  </script>
            </th>
             <th> <%= review.body %></th>
             <th><% if review.user == current_user %>
                  <div class="review-delete">
                    <%= link_to "削除", comic_review_path(review.comic, review), method: :delete %>
                  </div>
                <% end %></th>
            </tr>
           </tbody>
            <% end %>
         </table>
    </div>
    </div>
</div>



</div>










<script>
  $('#star').raty({
   size: 36,
   starOn: "<%= asset_path('star-on.png') %>",
   starOff: "<%= asset_path('star-off.png') %>",
   starHalf: "<%= asset_path('star-half.png') %>",
   scoreName: 'review[rate]',
   half: true,
   readOnly: true,
   score: "<%= @comic.reviews.average(:rate).to_f.round(1) %>",
 });

 $('#form_star').raty({
   size: 36,
   starOn: "<%= asset_path('star-on.png') %>",
   starOff: "<%= asset_path('star-off.png') %>",
   starHalf: "<%= asset_path('star-half.png') %>",
   scoreName: 'review[rate]',
   half: true,
 });
</script>