config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  root to:  "homes#top"
  post '/' => 'homes#top'
   get "home/about" => "homes#about"
   get "comics/search" => "comics#search"
  resources :comics do
  resources :reviews, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  resources :genres, only: [:new, :show, :create, :destroy]
 resources :users, only: [:show, :edit, :update]
 
# ゲストログイン
  post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord

   belongs_to :user
   attachment :image
   has_many :reviews, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorited_users,  through: :favorites, source: :user 
   belongs_to :genre


   validates :image, presence: true
   validates :author, presence: true
   validates :publisher, presence: true
   validates :title, presence: true
    validates :genre_id, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(method,word)
    if method == "forward_match"
            @comics = Comic.where("title LIKE ?","#{word}%")
    elsif method == "backward_match"
            @comics = Comic.where("title LIKE ?","%#{word}")
    elsif method == "perfect_match"
            @comics = Comic.where(title: "#{word}")
    elsif method == "partial_match"
            @comics = Comic.where("title LIKE ?","%#{word}%")
    else
            @comics = Comic.all
    end
  end

  def reviewd?(user)
    cnt = self.reviews.where(user_id: user.id).count
    return (cnt > 0)
  end

  def not_reviewd?(user)
    cnt = self.reviews.where(user_id: user.id).count
    return (cnt <= 0)
  end


end

app/models/comic_comment.rb
class ComicComment < ApplicationRecord
  belongs_to :user
  belongs_to :comic



  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :comic
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :comics, dependent: :destroy
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :comic



  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

    validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
    }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :comics, dependent: :destroy
   has_many :reviews, dependent: :destroy
   attachment :profile_image
   has_many :favorites, dependent: :destroy
   has_many :favorited_comics, through: :favorites, source: :comic


end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :authenticate_user!
  

  def new
    @comic = Comic.new

  end

  def show
    @comic = Comic.find(params[:id])
    @review = Review.new
  end

  def index
    @comics = Comic.all
    @users = User.all
    @comics = Comic.page(params[:page]).reverse_order
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @genres = Genre.all
    else
      @genres = Genre.all
    end
  end

  def create
  @comic = Comic.new(comic_params)
  @comic.user_id = current_user.id
    if @comic.save
        redirect_to  comics_path
    else
        render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy
    @comic = Comic.find(params[:id])
    @comic.destroy
    redirect_to comics_path
  end

  def search
    method = params[:search_method]
    word = params[:search_word]
    @comics = Comic.search(method,word).page(params[:page]).reverse_order
    render :index
  end

  def correct_comic
        @comic = Comic.find_by(params[:id])
    unless @comic.user.id == current_user.id
      render  new_comic_path
    end
  end


  private
  def comic_params
    params.require(:comic).permit(:genre_id, :image, :title, :body, :author, :publisher, :is_active, :genre)
  end





end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    comic = Comic.find(params[:comic_id])
    favorite = current_user.favorites.new(comic_id: comic.id)
    favorite.save
    redirect_back(fallback_location: comic_favorites_path(comic))
  end

  def destroy
    comic = Comic.find(params[:comic_id])
    favorite = current_user.favorites.find_by(comic_id: comic.id)
    favorite.destroy
    redirect_back(fallback_location: comic_favorites_path(comic))
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  
  def new
    @genre = Genre.new
    @genres = Genre.all
  end


  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_back(fallback_location: root_path)
    else
      @genres = Genre.all
      render :new
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to new_genre_path
  end
  

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

   def top
      @all_ranks = Comic.find(Review.group(:comic_id).order('count(comic_id) desc').limit(5).pluck(:comic_id))
      review_ranks = {}
      @all_ranks.each.with_index(1) do |comic, i|
        review_ranks[comic.id] = comic.reviews.average(:rate).to_f.round(1)
      end
      sorted_review_ranks = review_ranks.sort_by { |_, v| v }.reverse.to_h
      @ranks = []

      sorted_review_ranks.each do |k,_|
          @all_ranks.each do |rank|
             if rank.id == k
                @ranks << rank
             end
          end
      end


      @all_rank = Comic.find(Favorite.group(:comic_id).order('count(comic_id) desc').limit(5).pluck(:comic_id))
   end

   def about
   end

   def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
   end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    comic = Comic.find(params[:comic_id])
    review = current_user.reviews.new(review_params)
    review.comic_id = comic.id
    review.save
    redirect_to comic
  end

  def destroy
    comic = Comic.find(params[:comic_id])
    Review.find_by(user_id: current_user, comic_id: comic).destroy
    redirect_to comic_path(params[:comic_id])
  end

  private

  def review_params
    params.require(:review).permit(:rate, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user,only: [:edit,:show]

  def show
    @user = User.find(params[:id])
    @comics = @user.favorited_comics.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def correct_user
      @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to comics_path
    end
  end



  private
  def user_params
    params.require(:user).permit(:email, :name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comic_comments_helper.rb
module ComicCommentsHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cominect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if user_signed_in? %>

     <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="#"><h2>Cominect</h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDoropdown" aria-controls="#navbarNavDoropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDoropdown">
        
         
          
          <ul class="navbar-nav ml-auto">
            
    



    <li class="nav-item active text-black-50">
        <i class= "fas fa-crown  navlink text-light "><%= link_to '人気作品 ', root_path, :style => "color: white;" %></i>
    </li>

    <li class="nav-item">
        <i class="fas fa-book navlink text-light"><%= link_to '作品一覧 ', comics_path, :style => "color: white;"  %></i>
    </li>

    <li class="nav-item">
        <i class= "fas fa-book-medical  navlink text-light"><%= link_to '作品投稿 ', new_comic_path, :style => "color: white;"  %></i>
    </li>

    <li class="nav-item">
      <i class="far fa-user navlink text-light"><%= link_to 'マイページ ', user_path(current_user.id), :style => "color: white;"  %></i>
    </li>

      <li class="nav-item">
        <i class="fas fa-sign-out-alt navlink text-light"><%= link_to "ログアウト ", destroy_user_session_path, method: :delete, :style => "color: white;"  %></i>
      </li>
    <% else %>

    <nav class="navbar navbar-expand-lg navbar-dark  bg-info">
        <a class="navbar-brand" href="#"><h2>Cominect</h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDoropdown" aria-controls="#navbarNavDoropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDoropdown">
          <ul class="navbar-nav mr-auto"><h2><%= link_to 'ゲストログイン（閲覧用）', homes_guest_sign_in_path, method: :post, :style => "color: yellow;"  %></h2></ul>
          <ul class="navbar-nav ml-auto">


      <li class="nav-item">
         <i class= "fas fa-crown  navlink text-light"><%= link_to '人気作品', root_path, :style => "color: white;"  %></i>
      </li>

      <li class="nav-item active">
        <i class="fab fa-airbnb navlink text-light"><%= link_to 'ABOUT ', home_about_path, :style => "color: white;"  %></i>
      </li>

      <li class="nav-item">
         <i class="far fa-user navlink text-light"><%= link_to "新規登録", new_user_registration_path, :style => "color: white;"  %></i>
      </li>

      <li class="nav-item">
        <i class="fas fa-sign-out-alt navlink text-light"><%= link_to "ログイン", new_user_session_path, :style => "color: white;"  %></i>
      </li>
    <% end %>

    </header>
    <%= yield %>


  </body>
  
  <div class="container content">
</div>
<div class="footer bg-info">
   <div class="container">
      Copyright © 2021 cominect All Rights Reserved.  
   </div>
</div>
</html>